### ISSUE TITLE
Qt6 port

### ISSUE THREAD

**Issue by marc-sturm** [imgag/ngs-bits#628]

**Comment by ubuntolog** [comment]
I am working on this branch at the moment [qt6_switch](https://github.com/imgag/ngs-bits/tree/qt6_switch)

**Comment by ubuntolog** [comment]
The branch compiles with Qt 5.15 and does not show any warnings now. Unfortunately, I could not compile it with Qt 6. Entire modules have been removed: e.g. xmlpatterns

**Comment by ubuntolog** [comment]
The new branch cannot be compiled with Qt 5.12: I am getting an error "endl is not a member of Qt"

**Comment by ubuntolog** [comment]
The master branch now includes the code compatible with qt 5.15 and when compiling with qt 5.15 no warnings will be displayed. For the switch to Qt 6 the following things have to be considered:

- [ ] Removal of xmlpatterns module and its replacement with a third-party library (possibly libxml2)
- [ ] The remaining expressions using QRegExp need to be replaced with QRegularExpression, exactMatch method was removed, use match and hasMatch with some modifitions
- [ ] QT_CHARTS_USE_NAMESPACE replaced by a regular import #include <QtCharts/QChartView>
- [ ] QGridLayout::setMargin replaced by setContentsMargins
- [ ] QTextStream::setCodec("UTF-8") replaced by QTextCodec::codecForName("UTF-8");
- [ ] count() and size() method return new types, which causes problems in std::max statements, static_cast is not a good option
- [ ] QSvgRenderer replaced by <QtSvg/QSvgRenderer> and QPainter, adjust and test SVG rendering
- [ ] QT += network is needed for almost every project file

Without the above mentioned changes the code cannot be compiled with Qt 6. There will be around 300 warnings after that, and they have to be addressed.

**Comment by ubuntolog** [comment]
Post on qsizetype: https://forum.qt.io/topic/139340/what-exactly-is-qsizetype-and-what-is-it-s-purpose

**Comment by ubuntolog** [comment]
**Some statistics from GitHub Actions**

Build time with Qt 6.4 - 36:46 min
Build time with Qt 5.15 - 16:54 min

Running tests with Qt 6.4 - 3:42 min
Running tests with Qt 5.15 - 3:16 min
